### ISSUE TITLE
Caused by: java.lang.NullPointerException  at BaseNowplayingFragment.java:303

### ISSUE THREAD

**Issue by MrShuHong** [naman14/Timber#166]
`03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime: FATAL EXCEPTION: main
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime: Process: com.naman14.timber, PID: 24170
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.naman14.timber/com.naman14.timber.activities.NowPlayingActivity}: java.lang.NullPointerException
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:141)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5072)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:  Caused by: java.lang.NullPointerException
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTintList(DrawableWrapperDonut.java:272)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.graphics.drawable.DrawableWrapperDonut.setCompatTint(DrawableWrapperDonut.java:267)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.graphics.drawable.DrawableCompatBase.setTint(DrawableCompatBase.java:36)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.graphics.drawable.DrawableCompat$BaseDrawableImpl.setTint(DrawableCompat.java:89)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.graphics.drawable.DrawableCompat.setTint(DrawableCompat.java:380)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.util.TintHelper.tintDrawable(TintHelper.java:353)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.util.TintHelper.setTintSelector(TintHelper.java:115)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.util.TintHelper.setTintAuto(TintHelper.java:180)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.processors.DefaultProcessor.processTagPart(DefaultProcessor.java:187)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.processors.DefaultProcessor.process(DefaultProcessor.java:36)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.processors.DefaultProcessor.process(DefaultProcessor.java:21)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.ATE.performDefaultProcessing(ATE.java:65)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.ATE.apply(ATE.java:90)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.ATE.apply(ATE.java:94)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.ATE.apply(ATE.java:222)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.naman14.timber.nowplaying.BaseNowplayingFragment.onViewCreated(BaseNowplayingFragment.java:303)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.afollestad.appthemeengine.ATEActivity.onStart(ATEActivity.java:29)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.naman14.timber.activities.BaseActivity.onStart(BaseActivity.java:71)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:5259)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2174)
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:141) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5072) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
03-16 15:38:05.095 24170-24170/com.naman14.timber E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) `

**Comment by viacheslavokolitiy** [comment]
Could you format this logcat output, please  ?

**Comment by MrShuHong** [comment]
is  my proplem.  it is version's pronlem

**Comment by MrShuHong** [comment]
is my problem.  it is version problem.
