### ISSUE TITLE
Crash after open Applications

### ISSUE THREAD

**Issue by tuandq2711** [naman14/Timber#174]
Hey, Crash after open Applications short time. I have version 0.14b. My logcat:
`java.lang.NoSuchMethodError: android.widget.EdgeEffect.setColor
                                                                      at com.afollestad.appthemeengine.util.EdgeGlowUtil.setEdgeGlowColor(EdgeGlowUtil.java:102)
                                                                      at com.afollestad.appthemeengine.util.EdgeGlowUtil.setEdgeGlowColor(EdgeGlowUtil.java:86)
                                                                      at com.afollestad.appthemeengine.util.EdgeGlowUtil$1.onScrollStateChanged(EdgeGlowUtil.java:66)
                                                                      at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3990)
                                                                      at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1219)
                                                                      at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2508)
                                                                      at android.view.View.dispatchTouchEvent(View.java:7324)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2199)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1934)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
                                                                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1948)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1974)
                                                                      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1426)
                                                                      at android.app.Activity.dispatchTouchEvent(Activity.java:2417)
                                                                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1922)
                                                                      at android.view.View.dispatchPointerEvent(View.java:7504)
                                                                      at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3356)
                                                                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3301)
                                                                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4436)
                                                                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4415)
                                                                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4507)
                                                                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
                                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                      at android.os.MessageQueue.next(MessageQueue.java:125)
                                                                      at android.os.Looper.loop(Looper.java:124)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5159)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:810)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:577)
                                                                      at dalvik.system.NativeStart.main(Native Method)`

Thank!!!!!!!!!!!!!!!!!!

**Comment by jiansheliuxing** [comment]
I have met the same problem.
Because the method setColor is only supported above API 21.
So, if below 21,it will crash.
But, the EdgeGlowUtil doesn't handle that.
Even worse, it can't be override

**Comment by FeverCombo3** [comment]
i have the same problem。when i run app below api 21 ，it will crash，how to solve this problem？

**Comment by 15914415934** [comment]
i have try to overrride,but it is still called somewhere that i could't find
