### ISSUE TITLE
on Android 4.3 API 18 FOUND java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by brainysoon** [naman14/Timber#194]
## When i tring to running Timber on API level 18 and scroll the menu to bottom, I funod this error. And i can figure it out.
`07-25 10:10:38.502 30119-30119/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NoSuchMethodError: android.widget.EdgeEffect.setColor
                                                       at com.afollestad.appthemeengine.util.EdgeGlowUtil.setEdgeGlowColor(EdgeGlowUtil.java:102)
                                                       at com.afollestad.appthemeengine.util.EdgeGlowUtil.setEdgeGlowColor(EdgeGlowUtil.java:86)
                                                       at com.afollestad.appthemeengine.util.EdgeGlowUtil$1.onScrollStateChanged(EdgeGlowUtil.java:66)
                                                       at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3990)
                                                       at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1219)
                                                       at android.support.v7.widget.RecyclerView.cancelTouch(RecyclerView.java:2536)
                                                       at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2514)
                                                       at android.view.View.dispatchTouchEvent(View.java:7384)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2179)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1940)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2181)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2181)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1954)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1998)
                                                       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1431)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2484)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1946)
                                                       at android.view.View.dispatchPointerEvent(View.java:7564)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3909)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3792)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3387)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3437)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3406)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3491)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3414)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3548)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3387)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3437)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3406)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3414)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3387)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5445)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5425)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5396)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5519)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
                                                       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                   	at android.view.InputEventRec
`

**Comment by kensoon** [comment]
Can anybody help me figure this out ? thanks anyway!

**Comment by naman14** [comment]
Should be fixed now
