### ISSUE TITLE
A few issues 

### ISSUE THREAD

**Issue by Technologx** [naman14/Timber#261]
How do I set this app what do I need to do I installed the plugin and signed up on their site?
This also shows up in my gradle console:

````
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
````

Also when I select folders the app crashes.

````
E/RecyclerView: No adapter attached; skipping layout
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.technologx.blaze.player, PID: 20303
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:304)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.NullPointerException: storage == null
                      at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
                      at java.util.Arrays.asList(Arrays.java:155)
                      at com.technologx.blaze.player.dataloaders.FolderLoader.getMediaFiles(FolderLoader.java:31)
                      at com.technologx.blaze.player.adapters.FolderAdapter.updateDataSet(FolderAdapter.java:110)
                      at com.technologx.blaze.player.adapters.FolderAdapter.<init>(FolderAdapter.java:59)
                      at com.technologx.blaze.player.fragments.FoldersFragment$loadFolders.doInBackground(FoldersFragment.java:102)
                      at com.technologx.blaze.player.fragments.FoldersFragment$loadFolders.doInBackground(FoldersFragment.java:96)
                      at android.os.AsyncTask$2.call(AsyncTask.java:292)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                      at java.lang.Thread.run(Thread.java:818) 
E/RecyclerView: No adapter attached; skipping layout
````
Not sure if anyone else noticed this but the app does a lot of crashing even on certain now playing screen types. The 2nd now playing crashes & playlists crashes I figured I'd let you know about those issues as well.

**Comment by Technologx** [comment]
I'm really needing help with this please?
