### ISSUE TITLE
Folders View working with Android 4.4 but not working, force close in Android 6.0.1

### ISSUE THREAD

**Issue by hoadn** [naman14/Timber#273]
I have tried the app with Folders View, I can view the music file but tap on music, there is nothing happen. It's not working.
About the Android 6.0.1 it's force close. The message is like:
`FATAL EXCEPTION: AsyncTask #2
                                                                              Process:   ##com.naman14.timber, PID: 24723
                                                                              java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                  at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                  at java.lang.Thread.run(Thread.java:818)
                                                                               Caused by: java.lang.NullPointerException: storage == null
                                                                                  at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
                                                                                  at java.util.Arrays.asList(Arrays.java:155)
                                                                                  at com.naman14.timber.dataloaders.FolderLoader.getMediaFiles(FolderLoader.java:31)
                                                                                  at com.naman14.timber.adapters.FolderAdapter.updateDataSet(FolderAdapter.java:110)
                                                                                  at com.naman14.timber.adapters.FolderAdapter.<init>(FolderAdapter.java:59)
                                                                                  at com.naman14.timber.fragments.FoldersFragment$loadFolders.doInBackground(FoldersFragment.java:102)
                                                                                  at com.naman14.timber.fragments.FoldersFragment$loadFolders.doInBackground(FoldersFragment.java:96)
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)`

**Comment by naman14** [comment]
`listFiles` only returns null if specified file is not directory or there is an I/O exception. I have added a check for directory before calling list files

**Comment by hoadn** [comment]
It's seem that, folder view only View the SDCard. If phone not have SDcard, it's will not show any result. 
I have test the folder view, it's not force close anymore, but nothing happen when touch on mp3 files, the player not play the folder on Anroid 4.4, on Android 6.0 there is nothing in the folder. 
I have add the Sdcard and music in the card, but nothing happen.

More over, Could you add a file counts on each folder have sounds files. That's would very helpful for people who looking for their music folder.
