### ISSUE TITLE
NumberFormatException after texting in special input

### ISSUE THREAD

**Issue by seg-ha** [naman14/Timber#450]
E/AndroidRuntime(17528): FATAL EXCEPTION: main
E/AndroidRuntime(17528): Process: de.danoeh.antennapod, PID: 17528
E/AndroidRuntime(17528): java.lang.NumberFormatException: Invalid int: "1 days after finishing"
E/AndroidRuntime(17528): 	at java.lang.Integer.invalidInt(Integer.java:137)
E/AndroidRuntime(17528): 	at java.lang.Integer.parse(Integer.java:374)
E/AndroidRuntime(17528): 	at java.lang.Integer.parseInt(Integer.java:365)
E/AndroidRuntime(17528): 	at java.lang.Integer.parseInt(Integer.java:331)
E/AndroidRuntime(17528): 	at de.danoeh.antennapod.preferences.PreferenceController.buildEpisodeCleanupPreference(PreferenceController.java:842)
E/AndroidRuntime(17528): 	at de.danoeh.antennapod.preferences.PreferenceController.onCreate(PreferenceController.java:167)
E/AndroidRuntime(17528): 	at de.danoeh.antennapod.activity.PreferenceActivity$MainFragment.onCreatePreferences(PreferenceActivity.java:153)
E/AndroidRuntime(17528): 	at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:224)
E/AndroidRuntime(17528): 	at de.danoeh.antennapod.activity.PreferenceActivity$MainFragment.onCreate(PreferenceActivity.java:142)
E/AndroidRuntime(17528): 	at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
E/AndroidRuntime(17528): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
E/AndroidRuntime(17528): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(17528): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17528): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(17528): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(17528): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17528): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(17528): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(17528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(17528): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Bawya1098** [comment]
@seg-ha could yu please post steps to reproduce as well?
