### ISSUE TITLE
Timber crashes unexpectedly after denying permission in system settings

### ISSUE THREAD

**Issue by sjl872964789** [naman14/Timber#458]
**Describe the bug**
Timber crashes unexpectedly after denying permission in system settings

Device: [galaxy a6s]
OS version: [Android 8.1.0]
App version: [1.6.0]

**Steps to reproduce the behavior**
1. Install and open timber
2. Deny permission in system settings
3. Open timber again

**Carsh logcat**
```
08-22 11:15:50.029 10853 10919 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
08-22 11:15:50.029 10853 10919 E AndroidRuntime: Process: naman14.timber, PID: 10853
08-22 11:15:50.029 10853 10919 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
08-22 11:15:50.029 10853 10919 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/artists from pid=10853, uid=10149 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2005)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at com.naman14.timber.dataloaders.ArtistLoader.makeArtistCursor(ArtistLoader.java:71)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at com.naman14.timber.dataloaders.ArtistLoader.getAllArtists(ArtistLoader.java:53)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at com.naman14.timber.fragments.ArtistFragment$loadArtists.doInBackground(ArtistFragment.java:170)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at com.naman14.timber.fragments.ArtistFragment$loadArtists.doInBackground(ArtistFragment.java:165)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-22 11:15:50.029 10853 10919 E AndroidRuntime:        ... 4 more
08-22 11:15:50.044 10853 10922 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
08-22 11:15:50.044 10853 10922 E AndroidRuntime: Process: naman14.timber, PID: 10853
08-22 11:15:50.044 10853 10922 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
08-22 11:15:50.044 10853 10922 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/albums from pid=10853, uid=10149 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2005)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at com.naman14.timber.dataloaders.AlbumLoader.makeAlbumCursor(AlbumLoader.java:73)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at com.naman14.timber.dataloaders.AlbumLoader.getAllAlbums(AlbumLoader.java:55)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at com.naman14.timber.fragments.AlbumFragment$loadAlbums.doInBackground(AlbumFragment.java:198)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at com.naman14.timber.fragments.AlbumFragment$loadAlbums.doInBackground(AlbumFragment.java:193)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-22 11:15:50.044 10853 10922 E AndroidRuntime:        ... 4 more
08-22 11:15:50.058 10853 10926 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
08-22 11:15:50.058 10853 10926 E AndroidRuntime: Process: naman14.timber, PID: 10853
08-22 11:15:50.058 10853 10926 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:353)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
08-22 11:15:50.058 10853 10926 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=10853, uid=10149 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2005)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:756)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:705)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:663)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at com.naman14.timber.dataloaders.SongLoader.makeSongCursor(SongLoader.java:155)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at com.naman14.timber.dataloaders.SongLoader.makeSongCursor(SongLoader.java:146)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at com.naman14.timber.dataloaders.SongLoader.getAllSongs(SongLoader.java:123)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at com.naman14.timber.fragments.SongsFragment$loadSongs.doInBackground(SongsFragment.java:151)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at com.naman14.timber.fragments.SongsFragment$loadSongs.doInBackground(SongsFragment.java:145)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-22 11:15:50.058 10853 10926 E AndroidRuntime:        ... 4 more
```

**Screenshots**
Recorded video see attachment
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/15941953/90947740-c8844780-e46a-11ea-86cc-70c84badb05a.gif)

**Comment by sjl872964789** [comment]
Hi，any update about this issue？It would be really appreciated to get your concern on this.
