### ISSUE TITLE
Find some crashes

### ISSUE THREAD

**Issue by LvZW1895** [naman14/Timber#470]
APK Version : 1.8
AndroidOS Version = 9.0
**Description information：**
These crashes happened by accident when I was testing in different devices. I tried to reproduce them and found that they can't be reproduced, but they are real. I hope they can help you to debug.

**Crash 1:**
Long Msg: java.lang.IllegalStateException
	at android.os.Parcel.readException(Parcel.java:1692)
	at android.os.Parcel.readException(Parcel.java:1637)
	at com.naman14.timber.ITimberService$Stub$Proxy.getAudioSessionId(ITimberService.java:1195)
	at com.naman14.timber.MusicPlayer.getAudioSessionId(MusicPlayer.java:323)
	at com.naman14.timber.utils.TimberUtils.createEffectsIntent(TimberUtils.java:153)
	at com.naman14.timber.utils.TimberUtils.hasEffectsPanel(TimberUtils.java:147)
	at com.naman14.timber.activities.BaseActivity.onCreateOptionsMenu(BaseActivity.java:277)
	at com.naman14.timber.activities.MainActivity.onCreateOptionsMenu(MainActivity.java:298)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3316)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:620)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Crash 2:**
Long Msg: java.lang.ArrayIndexOutOfBoundsException: length=33; index=-1
	at java.util.ArrayList.get(ArrayList.java:413)
	at com.naman14.timber.adapters.SongsListAdapter$ItemHolder$1.run(SongsListAdapter.java:250)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
**Crash 3:**
Long Msg: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.fragment.app.Fragment.setNextAnim(int)' on a null object reference
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:772)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
**Crash 4:**
Long Msg: java.lang.IllegalArgumentException: setNextMediaPlayer failed.: status=0xFFFFFFED
	at android.media.MediaPlayer.setNextMediaPlayer(Native Method)
	at com.naman14.timber.MusicService$MultiPlayer.setNextDataSource(MusicService.java:2484)
	at com.naman14.timber.MusicService.setNextTrack(MusicService.java:1024)
	at com.naman14.timber.MusicService.setNextTrack(MusicService.java:1016)
	at com.naman14.timber.MusicService.access$1600(MusicService.java:99)
	at com.naman14.timber.MusicService$MusicPlayerHandler.handleMessage(MusicService.java:2295)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Crash 5:**
Long Msg: java.lang.RuntimeException: Unable to start activity ComponentInfo{naman14.timber/com.naman14.timber.activities.MainActivity}: java.lang.IllegalStateException: Unknown URL: content://media/external/audio/media/-1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
Caused by: java.lang.IllegalStateException: Unknown URL: content://media/external/audio/media/-1
	at android.os.Parcel.readException(Parcel.java:1692)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
	at com.naman14.timber.subfragments.LyricsFragment.getRealPathFromURI(LyricsFragment.java:119)
	at com.naman14.timber.subfragments.LyricsFragment.loadLyrics(LyricsFragment.java:60)
	at com.naman14.timber.subfragments.LyricsFragment.onCreateView(LyricsFragment.java:48)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at com.afollestad.appthemeengine.ATEActivity.onStart(ATEActivity.java:29)
	at com.naman14.timber.activities.BaseActivity.onStart(BaseActivity.java:140)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6887)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2703)
	... 9 more
crashend

**Comment by rahulyadav07** [comment]
can you please provide full details how can i reproduce those issue in my application . while raising the issue please provide the proper details related to creash or bug .

**Comment by Tysoftwares** [comment]
Join the telegram channel for aviator predictor purchase and make money from home everyday https://t.me/aviatorapp01
