### ISSUE TITLE
Getting error on running app

### ISSUE THREAD

**Issue by TheOrangeTester** [naman14/Timber#95]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.turbo.musicplayer/com.naman14.timber.activities.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.design.widget.NavigationView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                    Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.design.widget.NavigationView
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(Unknown Source)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
                                                       at com.naman14.timber.activities.MainActivity.onCreate(Unknown Source)
                                                       at android.app.Activity.performCreate(Activity.java:6010)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                       at android.app.Act

**Comment by zeustl** [comment]
Are you sure you've done the refactoring correct. It look like you are using com.turbo.musicplayer and still have references to *timber.

Change all your references and try again.

**Comment by okungnyo** [comment]
What is com.turbo.musicplayer and why does it have references to Timber??

(Sorry, I'm just a passerby and I got curious.)

**Comment by naman14** [comment]
@okungnyo https://play.google.com/store/apps/details?id=com.turbo.musicplayer
@TheOrangeTester Don't make a new issue if you are having crashes in ripping off

**Comment by okungnyo** [comment]
What is it and why hasn't it been taken down??
